### ISSUE TITLE
Sound Volume

### ISSUE THREAD

**Issue by SebOvs** [noelportugal/google-home-notifier#17]
how increase the volume before play sound ?

**Comment by btrial** [comment]
I would also like to know if it is possible to control the volume somehow ? In my case I would like to decrease it as it sounds very loud.

**Comment by markosole** [comment]
Hi guys, did you find a way to control the volume? I would like to increase it as well. Thx

**Comment by alexisohayon** [comment]
+1

**Comment by tinoue** [comment]
Made PR to add volume() API.
https://github.com/noelportugal/google-home-notifier/pull/44
