### ISSUE TITLE
use same ngrok url every time

### ISSUE THREAD

**Issue by jorgyz** [noelportugal/google-home-notifier#3]
First of all, thanks for this -- it's working great on my Pi.  Second, is there a way to use a fixed ngrok url, rather than a new one being generated every time?

**Comment by jorgyz** [comment]
Nevermind, it seems you have to upgrade to a paid ngrok plan to use a custom subdomain.

**Comment by OpenDog** [comment]
We have a tool called bst proxy. It is free and doesn't change the url. Look [here].(https://bespoken.tools)
