### ISSUE TITLE
CANNOT excute "node example.js"

### ISSUE THREAD

**Issue by bun-git** [noelportugal/google-home-notifier#35]
Hi there. 
I tried installing and running "node example.js" following this README but failed.
I got a error below.

>/home/bun/Downloads/google-home-notifier/node_modules/mdns/lib/browser.js:86
  dns_sd.DNSServiceBrowse(self.serviceRef, flags, ifaceIdx, '' + requested_type,
         ^

> Error: dns service error: unknown
>     at new Browser (/home/bun/Downloads/google-home-notifier/node_modules/mdns/lib/browser.js:86:10)
>     at Object.create [as createBrowser] (/home/bun/Downloads/google-home-notifier/node_modules/mdns/lib/browser.js:114:10)
>     at Object.<anonymous> (/home/bun/Downloads/google-home-notifier/google-home-notifier.js:4:20)
>     at Module._compile (module.js:641:30)
>     at Object.Module._extensions..js (module.js:652:10)
>     at Module.load (module.js:560:32)
>     at tryModuleLoad (module.js:503:12)
>     at Function.Module._load (module.js:495:3)
>     at Module.require (module.js:585:17)
>     at require (internal/module.js:11:18)
> 

Can anyone help me out?

My environment is,
Xubuntu(on Chromebook)
node -v : v9.2.1
npm -v : 5.5.1

Thank you in advance.

**Comment by bun-git** [comment]
off course I completed " After npm install" step.

**Comment by pilyx** [comment]
Hi,

I have the same issue and haven't managed to solve it as well..

**Comment by bun-git** [comment]
solved it!
I replaced mdns to mdns-js and it worked.

pilyx, please try editing package.json and google-home-notifier.js.
see the link below (japanese site though).
https://qiita.com/tkyko13/items/163e80d3b65543d6a9da#_reference-2b80e6878f96b21b1c07

I'll try to help you solve this.

**Comment by pilyx** [comment]
Hi !
Thank you bun-git. Works perfectly now!

Cheers

**Comment by bun-git** [comment]
great!
