### ISSUE TITLE
How to bypass the bip before each message

### ISSUE THREAD

**Issue by JBX028** [noelportugal/google-home-notifier#42]
Hi,
I was wondering if there is a way to use a parameter to avoid my google home to play a short sound before talking. In some cases, it's useful but sometime it's not. I am using this library with ifttt to let my device to answer questions and this sound is not necessary for this scenario.
I have checked the source code and also the one for node-castv2-client and I didn't see anything. Perhaps it's something hardcoded in google home?
Any idea?

Thanks

**Comment by kokarn** [comment]
As far as i know it's the sound the device makes when you connect to it
which makes it impossible to circumvent.

**Comment by JBX028** [comment]
Hi,
Ok thanks for the fast reply. This is indeed what I thought as well.....
