### ISSUE TITLE
get key failed from google

### ISSUE THREAD

**Issue by philpownall** [noelportugal/google-home-notifier#46]
I've been happily using google-home-notifier for quite some time, but have recently started encountering this error:

Error: get key failed from google
    at /home/pi/MyHouse/node_modules/google-tts-api/lib/key.js:27:13
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)

The error message originates in the key.js module as indicated:
   try {
      eval(html.match(/TKK=eval\(\'\(.*\)\'\);/g)[0]);  // TKK = '405291.1334555331'
      if (TKK === null) throw null;
    } catch (e) {
      throw new Error('get key failed from google');
    }

I've tried removing and reinstalling node.js and google-home-notifier, I've tried rebooting the Google Home, and I've tried calling googlehome.device and googlehome.ip to no avail ; does anyone have any idea where I go from here?  Is it some sort of authorization error from google?

**Comment by tani-github** [comment]
me too.
I've been happily using google-home-notifier for quite some time, but
I also saw the same error today.
Will it be fixed?

-status 
rasbery pi  -> google-home-notifier ->  googlehome 
-error 
Error: get key failed from google
    at /home/pi/dev/google-home-notifier/node_modules/google-tts-api/lib/key.js:27:13
    at process._tickCallback (internal/process/next_tick.js:68:7)

I think that
can not acquire TKK by accessing this site(https://translate.google.com/) on rasberry pi.

**Comment by horihiro** [comment]
This is a problem which 'google-tts' must be fixed, not this library.
https://github.com/zlargon/google-tts/issues/13

And @ncpierson has already fixed this problem ( great work! ).
https://github.com/zlargon/google-tts/pull/14

So I think it works well by using next version of 'google-tts'.

**Comment by horihiro** [comment]
New version of `google-tts` is [released](https://github.com/zlargon/google-tts/releases/tag/0.0.3).
You have to update package.json of `google-home-notifier` and re-install.

Before

```
  "dependencies": {
      :
    "google-tts-api": "0.0.2",
      :
  }
```
After

```
  "dependencies": {
      :
    "google-tts-api": "0.0.3",
      :
  }
```

**Comment by cookemmm** [comment]
do you have the steps that need to be performed to complete the update and reinstall?

**Comment by philpownall** [comment]
Updated google-tts-api as indicated and verified that google homre notifier is happily making announcements again.

**Comment by sebsebseb1982** [comment]
Hi could you update google-home-notifier with this fix please ?

**Comment by specklesmike** [comment]
Note: 2019
In ~/.node-red/node_modules/google-home-notify`

edit package.json and change the dependency on 'google-tts-api' from '0.0.2-alpha1' to '0.0.3', so it reads:

"dependencies": {
"bluebird": "3.5.1",
"castv2-client": "^1.2.0",
"google-tts-api": "**0.0.4**"
}

Update the dependency
`npm update`

Restart node-red
`node-red-stop`
`node-red-start`

**Comment by cgmckeever** [comment]
Not sure why this isn;t updated in `Master`, but I just proposed a quick PR for it. Seems to be the fix, at least for me
