### ISSUE TITLE
Unable to start srcript

### ISSUE THREAD

**Issue by lcherukuri** [noelportugal/google-home-notifier#48]
Error: get key failed from google
    at /Users/lc/Documents/work/GoogleHomeNotifications/node_modules/google-home-notifier/node_modules/google-tts-api/lib/key.js:27:13
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)

This problem started recently.

**Comment by horihiro** [comment]
it seems to be same as #46 .
you should use latest google-tts if it does.

**Comment by horihiro** [comment]
currently, you should google-tts@0.0.4 according to https://github.com/noelportugal/google-home-notifier/pull/47#issuecomment-443238911
